version: "2"
services:
  mrtg:
    build: .
    hostname: mrtg
    restart: always
    ports:
      - "8880:80"
    volumes:
      - "./conf.d:/etc/mrtg/conf.d"
      - "./html:/usr/share/nginx/html"
    environment:
        TZ: "Brazil/East"
        HOSTS: 'public:192.168.0.123'
    tmpfs:
      - "/run"
